### ISSUE TITLE
Operation documentation lack complext type for the operation input parameter and the resturn also. 

### ISSUE THREAD

**Issue by alan-techdev** [mulesoft/docs-mule-sdk#145]
There should be a better documentation to reflect the complex type in the return based on OutputTypeResolver and the  input parameter base on InputTypeResolver.

**Comment by sathya0** [comment]
Hi @alanmehio, thanks for your feedback. We updated the docs in this PR: https://github.com/mulesoft/docs-mule-sdk/pull/208
